title: kmg.com
description: "Satellite - jekyll blog theme"
logo_img: "/assets/img/favicon.webp"
profile_img: "https://i.namu.wiki/i/1jHABtbEv6mIPFMuJWyJX8dF8mr6-mBHzLK1ZI-Qn7ZmAfu2BAb3bGpMhUdsh767wrem5U3yiwE6qB2G_KuhCC4eYmJ2JNQVjnHX5NMG4ZHltDcBykgpg7Uajzu_1lhdwhTWRhUBIGQE23l0_e9Fv3-HczamWtkEo3dHAdeBBDY.webp"

# Social Links
email: prcsc05@gmail.com
github_username: kdt-kmg
instagram_username: kimmingyu0515
linkedin_username: x


# External API 
# giscus add 1-4
data-repo="kdt-kmg/kdt-kmg.github.io"
data-repo-id="R_kgDOO3ehrA"
data-category="Q&A"
data-category-id="DIC_kwDOO3ehrM4CrJZE"
goatcounter_code: kmg
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
